feat(api): Expose Markdown Editor API in Angular Component
Teradata/covalent-text-editor-nightly pull request #2
Opened 2017-08-08 17:16 UTC by jeremysmartt

## Description
Exposing the instantiation options and methods in the Angular Component

### Test Steps
- [ ] Checkout branch
- [ ] npm install
- [ ] npm run build
- [ ] cd deploy/platform/text-editor
- [ ] npm pack (prints out a tgz file created)
- [ ] pwd (prints out your < path > you are at)
- [ ] Go to Covalent repo
- [ ] rm -rf node_modules/`@covalent`/text-editor
- [ ] npm install < path > / < tgz file created >
- [ ] edit the demo for code-editor.component.html and add the following:
```html
    <div layout="row" layout-align="start center">
      <td-text-editor [options]="opts"></td-text-editor>
    </div>
```
- [ ] edit the demo for code-editor.component.ts and add the following options from here: https://github.com/sparksuite/simplemde-markdown-editor#configuration
```javascript
opts: any = {
    lineWrapping: true,
    toolbar: false,
    ...
  };
```
- [ ] edit the demo for components.module.ts and add the following:
```javascript
    import { CovalentTextEditorModule } from '../../../../node_modules/@covalent/text-editor';
```
under imports add:
```javascript
CovalentTextEditorModule
```
- [ ] ng serve
- [ ] In browser go to: http://localhost:4200/#/components/code-editor
- [ ] See Markdown Editor running
- [ ] Use some of the functionality and see works

#### Screenshots
![screen shot 2017-08-04 at 2 08 53 pm](https://user-images.githubusercontent.com/10502797/28987051-86cd5346-791e-11e7-8a0f-4331e3f64ead.png)

2017-08-08 17:19 UTC, kyleledbetter commented on docs/SETUP.md
> +  opts: any = {
would it hurt to just call `opts` `options` instead? :)

2017-08-08 20:32 UTC, jeremysmartt commented on docs/SETUP.md
> +  opts: any = {
:) sure

2017-08-08 22:07 UTC, emoralesb05 commented on docs/API.md
> +<td-text-editor [value]="Some Text" options="options"></td-text-editor>
`options` should be `[options]` here

2017-08-08 22:09 UTC, emoralesb05 requested changes

2017-08-08 22:09 UTC, emoralesb05 commented on docs/SETUP.md
> +<td-text-editor [value]="Some Text" options="options"></td-text-editor>
same here

2017-08-08 22:09 UTC, emoralesb05 commented on src/platform/text-editor/text-editor.component.ts
> +    this._simpleMDE = new SimpleMDE(this.options);
does passing an empty object override everything?

2017-08-08 22:48 UTC, jeremysmartt commented on src/platform/text-editor/text-editor.component.ts
> +    this._simpleMDE = new SimpleMDE(this.options);
nope, all good

2017-08-09 16:41 UTC, emoralesb05 approved these changes

2017-08-09 16:42 UTC, merged